// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMEi-r_ZRq-SD51zu8O1PZ4ZAcQzlELc',
    appId: '1:861016329535:web:e9e5b4d81d270a3e60578a',
    messagingSenderId: '861016329535',
    projectId: 'authentication-6c5b3',
    authDomain: 'authentication-6c5b3.firebaseapp.com',
    storageBucket: 'authentication-6c5b3.appspot.com',
    measurementId: 'G-5G6JP6GVWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKYzslw7teluD0Sla70mIkU9ufYkH7aQ',
    appId: '1:861016329535:android:9c78a5791cd4529660578a',
    messagingSenderId: '861016329535',
    projectId: 'authentication-6c5b3',
    storageBucket: 'authentication-6c5b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkar09W26AkbeKsbiaNCO4AJnBRJb_ayg',
    appId: '1:861016329535:ios:8d7f53e578d502ee60578a',
    messagingSenderId: '861016329535',
    projectId: 'authentication-6c5b3',
    storageBucket: 'authentication-6c5b3.appspot.com',
    iosClientId: '861016329535-i1fnpppni0omdjdut1ndk91k70jk1vqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppWithApi',
  );
}
